version: 2.1
jobs:
  build:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Terraform init
          command: |
            terraform init
      - run: 
          name: Terraform plan
          command: |
            terraform plan
      - when:
          condition:
            equal: [ main, << pipeline.git.branch >> ]
          steps: 
            - run:
                name: Build ECS cluster
                command: |
                  terraform apply -input=false -auto-approve

workflows: 
  version: 2
  build_and_deploy: 
    jobs:
      - build
